### PR TITLE
Add a function to reload bind if there is a modification in the conf …

### PR DESCRIPTION
**Pull request by ghost**
…files

### CODE REVIEW

**Comment by pstauffer** [comment]
Hi,

Sorry I can't merge the pull request. I want only one active process active in the docker container.

If you need such a feature, it would be better to create a separate docker container just with the inotify function and reload the bind container, if a files has changed. Or run the inotify on the docker host and reload the bind container. I would prefer option 1.

Greets
Pascal

**Comment by ghost** [comment]
Nice idea to create a separate docker container for inotify !
But too complicate for me. It's working perfect like that, i'll keep like this.
Thank you for your bugfix !

**Comment by pstauffer** [comment]
I'll try it out... could be interesting  ;-)
By the way, I've created a new tag with the new feature & bugfixes -> v1.0.3

**Comment by pstauffer** [comment]
Check out my new docker container for inotify.
https://hub.docker.com/r/pstauffer/inotify/

I would recommend you to use a docker-compose file for bind & inoty together.

**Pull request closed without merging**
